# Generated by Django 3.1.7 on 2021-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='private_score',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='public_score',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(default='On checking', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='column_to_compare',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='private_reference_file',
            field=models.FileField(blank=True, null=True, upload_to='files/contests/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='public_reference_file',
            field=models.FileField(blank=True, null=True, upload_to='files/contests/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='region_of_interest',
            field=models.FileField(blank=True, null=True, upload_to='files/contests/%Y/%m/%d/'),
        ),
    ]
